apiVersion: apps/v1
kind: Deployment
metadata:
  name: boards-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boards
  template:
    metadata:
      labels:
        app: boards
    spec:
      containers:
        - name: boards
          image: ndhlovu/boards
          env:
            - name: JWT_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: BOARDS_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: BOARDS_MONGO_URI

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: CLOUDINARY_API_SECRET

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: PORT

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_CLUSTER_ID
              value: tuskui

            - name: NATS_URL
              value: "http:/nats-srv:4222/"
---
apiVersion: v1
kind: Service
metadata:
  name: board-srv
spec:
  selector:
    app: boards
  ports:
    - name: boards
      protocol: TCP
      port: 3000
      targetPort: 3000
