apiVersion: apps/v1
kind: Deployment
metadata:
  name: boards-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boards
  template:
    metadata:
      labels:
        app: boards
    spec:
      containers:
        - name: boards
          image: ndhlovu/boards
          env:
            - name: JWT_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: BOARDS_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: BOARDS_MONGO_URI

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: mongo-port
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: boards-srv
spec:
  selector:
    app: boards
  ports:
    - name: boards
      protocol: TCP
      port: 3000
      targetPort: 3000
