name: deploy-board-service

on:
  push:
    branches:
      - main
    paths:
      - "board-service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          token: ${{ secrets.PAT }}
      - run: cd board-service && docker build -t ndhlovu/board .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ndhlovu/board
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save tusks
      - run: kubectl rollout restart deployment board-depl
